### ISSUE TITLE
wavepacket2D: ordering in defining the potential V(x,y)

### ISSUE THREAD

**Issue by liuzheng1990** [qojulia/QuantumOptics.jl-examples#14]
Hi all,
I got one question when reading the "wavepacket2D" example carefully. In defining the 2D Gaussian potential, we have 
`potential(x,y) = exp((-x^2-y^2)/30.)
V = diagonaloperator(b_comp_x, [potential(x, y) for x in xsample for y in ysample]);`
I wonder whether the ordering in the square bracket is correct. Note that the for loop of y is nested inside the for loop of x. Therefore, the (xi,yj) term is the **(i-1)d + j** 's entry in the list. It seems to me that this ordering is the "kron" ordering, while qojulia uses the column-ordered convention.

So is it a mistake, or is it due to my own misunderstanding? Of couse, in this case of Guassian potential, it is symmetric between x and y. On the other hand, if I have an operator of the form `tensor(A(x),B(y))`, the problem by the ordering will matter. If we look at the action `Tensor(A(x),B(y))` on |x,y>, the (x,y) entry in the operator is at position **(x-1)d + y**, while the (x,y) entry of the ket is at position **x + (y-1)d**. It seems the operator matrix constructed in this way does not act on the correct column matrix of the state.

**Comment by david-pl** [comment]
Hi there!

Thanks for pointing that out. You are right, the example is wrong. Like you said, due to the symmetry that was quite easy to miss. Sorry about that.

You also were right about the solution to the problem: the nesting of the loops should be reversed:
```julia
V = diagonaloperator(b_comp_x, [potential(x, y) for y in ysample for x in xsample])
```

It's easy to check that this is correct in the example. In order to ensure that things come out correct, we can break the symmetry (that checks out even though there's an error) by simply changing the potential function to
```julia
potential(x,y) = exp(-x^2/30.0-y^2/10.)
```
The Gaussian potential function can separated, i.e. `e^(-x^2/30-y^2/10)=e^(-x^2/30)*e^(-y^2/10)`. Due to this special property, the potential operator can be written as a tensor product, like so
```julia
potential_x(x) = exp(-x^2/30.0)
potential_y(y) = exp(-y^2/10.0)
Vx = potentialoperator(b_position, potential_x)
Vy = potentialoperator(b_positiony, potential_y)
Vcomp = Vx ⊗ Vy
```
We can then compare the `Vcomp` operator to `V` which tells us that they are identical (up to rounding errors).

It might not be as easy to check this when the potential function is non-separable. Let me know if you are still having trouble in your use-case.

In the meantime I will correct the example.

**Comment by liuzheng1990** [comment]
Right. Simply swapping the two for-loops will do. Right, usually the potential is not separable, but the "diagonaloperator" trick should work in general, as long as we are careful of this ordering. Thanks very much!

**Comment by david-pl** [comment]
Agreed. Actually I think you shouldn't be bothered with keeping this in mind. This is why I implemented the `potentialoperator` for composite bases. You can check out the master branch to use it.

Now you can just do
```julia
potential(x,y) = exp(-(x^2 + y^2)/30.0)
V = potentialoperator(b_comp_x, potential)
```
The only thing to keep in mind here is that the `potential` function has to accept as many arguments as there are bases constituting the composite basis `b_comp_x` and that the arguments must have the same order as the tensor product. So, in the example since `b_comp_x = b_position ⊗ b_positiony` the function has to be `potential(x, y)` and not `potential(y, x)` (of course in the wavepacket2D example this wouldn't matter due to symmetry).

**Comment by liuzheng1990** [comment]
Great. This change is definitely more friendly to our intuition. Now everything about the lazy operators should be easy to use. I'll go on playing with them. Thanks very much, David!

**Comment by david-pl** [comment]
The updated example and the new API docs for the `potentialoperator` function are now on-line in the documentation so I'm closing this.
