### ISSUE TITLE
ArgumentError when using stiff solver algorithms for stochastic.master/master_dynamic

### ISSUE THREAD

**Issue by guruvamsi-policharla** [qojulia/QuantumOptics.jl-examples#22]
When using `alg=ISSEM()/ImplicitEM()` found at https://docs.sciml.ai/latest/solvers/sde_solve/ an ArgumentError is thrown. 

> "LoadError: ArgumentError: Cannot create a dual over scalar type Complex{Float64}. If the type behaves as a scalar, define FowardDiff.can_dual."

The exact modification I have done is:
`tout, ρt = stochastic.master(T, ρ0, H, J, C; rates=rates, alg=StochasticDiffEq.ISSEM())`

Presumably, this is because the Hamiltonian is complex and differentiating over complex numbers seems to be disabled by default in the ForwardDiff package.

Posting to ask if there's a workaround to this.

**Comment by david-pl** [comment]
ForwardDiff doesn't support complex dual numbers (yet). In principle you can turn off automatic differentiation with `ImplicitEM(autodiff=false)`. However, this is then incompatible with the default saving used in QuantumOptics.jl since you can no longer interpolate the solution. You have to ensure that `saveat` is empty such that the saving occurs only at steps which are actually taken by the solver. Unfortunately `saveat` was never part of the API.

I will merge a fix for this soon, so in a few hours from now this 
` tout, ρt = stochastic.master(T, ρ0, H, J, C; rates=rates, alg=StochasticDiffEq.ISSEM(autodiff=false), saveat=[])` should work when using the latest master branch.

**Comment by david-pl** [comment]
This fix is now released, so the workaround above should work on the latest version.
